<a href="https://colab.research.google.com/github/Gagankhera/Forsk_Projects/blob/main/ANN_Churn_Modelling.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
from google.colab import drive
drive.mount('/gdrive')

Mounted at /gdrive


In [ ]:
with open('/gdrive/My Drive/foo.txt', 'w') as f:
  f.write('Hello Google Drive!')
!cat '/gdrive/My Drive/foo.txt'

Hello Google Drive!

In [ ]:
import os
os.getcwd

<function posix.getcwd>

In [ ]:
os.chdir("/gdrive/My Drive/Deep_Learning")

In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
df = pd.read_csv("Churn_Modelling.csv")

In [ ]:
df.shape

(10000, 14)

In [ ]:
df.head()

RowNumber  CustomerId   Surname  ...  IsActiveMember EstimatedSalary Exited
0          1    15634602  Hargrave  ...               1       101348.88      1
1          2    15647311      Hill  ...               1       112542.58      0
2          3    15619304      Onio  ...               0       113931.57      1
3          4    15701354      Boni  ...               0        93826.63      0
4          5    15737888  Mitchell  ...               1        79084.10      0

[5 rows x 14 columns]

In [ ]:
df['Geography'].unique()

array(['France', 'Spain', 'Germany'], dtype=object)

Separating out features and labels
# Leaving out Rowno, Custid and surname from features as they are #system generated

In [ ]:
features = df.iloc[:,3:13].values
labels = df.iloc[:,13].values

In [ ]:
df.dtypes

RowNumber            int64
CustomerId           int64
Surname             object
CreditScore          int64
Geography           object
Gender              object
Age                  int64
Tenure               int64
Balance            float64
NumOfProducts        int64
HasCrCard            int64
IsActiveMember       int64
EstimatedSalary    float64
Exited               int64
dtype: object

In [ ]:
features

array([[619, 'France', 'Female', ..., 1, 1, 101348.88],
       [608, 'Spain', 'Female', ..., 0, 1, 112542.58],
       [502, 'France', 'Female', ..., 1, 0, 113931.57],
       ...,
       [709, 'France', 'Female', ..., 0, 1, 42085.58],
       [772, 'Germany', 'Male', ..., 1, 0, 92888.52],
       [792, 'France', 'Female', ..., 1, 0, 38190.78]], dtype=object)

In [ ]:
labels

array([1, 0, 1, ..., 1, 1, 0])

In [ ]:
# so here in our features, Geography and Gender are Categorical data, so perfoming oneHotEncodeing

In [ ]:
from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import ColumnTransformer

In [ ]:
cT = ColumnTransformer([('encoder', OneHotEncoder(), [1,2])], remainder='passthrough')

features = np.array(cT.fit_transform(features), dtype = np.float32)

In [ ]:
features[0:10,:]



array([[1.0000000e+00, 0.0000000e+00, 0.0000000e+00, 1.0000000e+00,
        0.0000000e+00, 6.1900000e+02, 4.2000000e+01, 2.0000000e+00,
        0.0000000e+00, 1.0000000e+00, 1.0000000e+00, 1.0000000e+00,
        1.0134888e+05],
       [0.0000000e+00, 0.0000000e+00, 1.0000000e+00, 1.0000000e+00,
        0.0000000e+00, 6.0800000e+02, 4.1000000e+01, 1.0000000e+00,
        8.3807859e+04, 1.0000000e+00, 0.0000000e+00, 1.0000000e+00,
        1.1254258e+05],
       [1.0000000e+00, 0.0000000e+00, 0.0000000e+00, 1.0000000e+00,
        0.0000000e+00, 5.0200000e+02, 4.2000000e+01, 8.0000000e+00,
        1.5966080e+05, 3.0000000e+00, 1.0000000e+00, 0.0000000e+00,
        1.1393157e+05],
       [1.0000000e+00, 0.0000000e+00, 0.0000000e+00, 1.0000000e+00,
        0.0000000e+00, 6.9900000e+02, 3.9000000e+01, 1.0000000e+00,
        0.0000000e+00, 2.0000000e+00, 0.0000000e+00, 0.0000000e+00,
        9.3826633e+04],
       [0.0000000e+00, 0.0000000e+00, 1.0000000e+00, 1.0000000e+00,
        0.0000000e+0

In [ ]:
features = features[:, 1:] #drop the first dummy column for Geography

features[0]


array([0.0000000e+00, 0.0000000e+00, 1.0000000e+00, 0.0000000e+00,
       6.1900000e+02, 4.2000000e+01, 2.0000000e+00, 0.0000000e+00,
       1.0000000e+00, 1.0000000e+00, 1.0000000e+00, 1.0134888e+05],
      dtype=float32)

In [ ]:
features = features[:, [0,1,3,4,5,6,7,8,9,10,11]] #drop the column for Gender

features.shape

features[0,:]

array([0.0000000e+00, 0.0000000e+00, 0.0000000e+00, 6.1900000e+02,
       4.2000000e+01, 2.0000000e+00, 0.0000000e+00, 1.0000000e+00,
       1.0000000e+00, 1.0000000e+00, 1.0134888e+05], dtype=float32)

In [ ]:
features.shape

(10000, 11)

In [ ]:
from sklearn.model_selection import train_test_split
features_train, features_test, labels_train, labels_test = train_test_split(features, labels, test_size = 0.2, random_state = 0)


In [ ]:

features[0]

array([0.0000000e+00, 0.0000000e+00, 0.0000000e+00, 6.1900000e+02,
       4.2000000e+01, 2.0000000e+00, 0.0000000e+00, 1.0000000e+00,
       1.0000000e+00, 1.0000000e+00, 1.0134888e+05], dtype=float32)

In [ ]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
features_train = sc.fit_transform(features_train)
features_test = sc.transform(features_test)

In [ ]:
features_train[0]

array([-0.56984437,  1.7430905 , -1.0916871 ,  0.16958177, -0.46460798,
        0.00666099, -1.2157176 ,  0.8095029 ,  0.64259493, -1.0322704 ,
        1.1064317 ], dtype=float32)

In [ ]:
# Importing the Keras libraries and packages
import keras
from keras.models import Sequential
from keras.layers import Dense

In [ ]:
classifier_model = Sequential()


In [ ]:
features.shape

(10000, 11)

In [ ]:
#adding the first hidden layer
classifier_model.add(Dense(units=6,kernel_initializer='uniform',activation='relu',input_dim = 11))

In [ ]:
#adding the second hidden layer
classifier_model.add(Dense(units=6,kernel_initializer='uniform',activation='relu'))


In [ ]:
#adding the output layer
classifier_model.add(Dense(units=1,kernel_initializer='uniform',activation='sigmoid'))

In [ ]:
#compiling th ANN
classifier_model.compile(optimizer = 'adam',loss='binary_crossentropy',metrics = ['accuracy'])


In [ ]:
classifier_model.fit(features_train,labels_train,batch_size=20,epochs=10)

Epoch 1/10
400/400 [==============================] - 1s 2ms/step - loss: 0.4189 - accuracy: 0.7960
Epoch 2/10
400/400 [==============================] - 1s 2ms/step - loss: 0.4180 - accuracy: 0.7960
Epoch 3/10
400/400 [==============================] - 1s 2ms/step - loss: 0.4171 - accuracy: 0.7960
Epoch 4/10
400/400 [==============================] - 1s 2ms/step - loss: 0.4161 - accuracy: 0.8029
Epoch 5/10
400/400 [==============================] - 1s 2ms/step - loss: 0.4153 - accuracy: 0.8246
Epoch 6/10
400/400 [==============================] - 1s 2ms/step - loss: 0.4148 - accuracy: 0.8289
Epoch 7/10
400/400 [==============================] - 1s 2ms/step - loss: 0.4136 - accuracy: 0.8281
Epoch 8/10
400/400 [==============================] - 1s 2ms/step - loss: 0.4130 - accuracy: 0.8292
Epoch 9/10
400/400 [==============================] - 1s 2ms/step - loss: 0.4128 - accuracy: 0.8290
Epoch 10/10
400/400 [==============================] - 1s 2ms/step - loss: 0.4117 - accuracy: 0.8292

In [ ]:
labels_pred = classifier_model.predict_classes(features_test)
#labels_pred = (labels_pred > 0.5)

/usr/local/lib/python3.7/dist-packages/keras/engine/sequential.py:450: UserWarning: `model.predict_classes()` is deprecated and will be removed after 2021-01-01. Please use instead:* `np.argmax(model.predict(x), axis=-1)`,   if your model does multi-class classification   (e.g. if it uses a `softmax` last-layer activation).* `(model.predict(x) > 0.5).astype("int32")`,   if your model does binary classification   (e.g. if it uses a `sigmoid` last-layer activation).
  warnings.warn('`model.predict_classes()` is deprecated and '


In [ ]:
labels_pred

array([[0],
       [0],
       [0],
       ...,
       [0],
       [0],
       [0]], dtype=int32)

In [ ]:


len(labels_pred)

2000

In [ ]:
list(zip(labels_test,labels_pred))

[(0, array([0], dtype=int32)),
 (1, array([0], dtype=int32)),
 (0, array([0], dtype=int32)),
 (0, array([0], dtype=int32)),
 (0, array([0], dtype=int32)),
 (1, array([1], dtype=int32)),
 (0, array([0], dtype=int32)),
 (0, array([0], dtype=int32)),
 (1, array([0], dtype=int32)),
 (1, array([1], dtype=int32)),
 (0, array([0], dtype=int32)),
 (0, array([0], dtype=int32)),
 (0, array([0], dtype=int32)),
 (0, array([0], dtype=int32)),
 (1, array([1], dtype=int32)),
 (1, array([0], dtype=int32)),
 (0, array([0], dtype=int32)),
 (0, array([0], dtype=int32)),
 (0, array([0], dtype=int32)),
 (0, array([0], dtype=int32)),
 (0, array([1], dtype=int32)),
 (0, array([0], dtype=int32)),
 (0, array([0], dtype=int32)),
 (0, array([0], dtype=int32)),
 (0, array([0], dtype=int32)),
 (0, array([0], dtype=int32)),
 (0, array([0], dtype=int32)),
 (0, array([0], dtype=int32)),
 (0, array([0], dtype=int32)),
 (0, array([0], dtype=int32)),
 (0, array([0], dtype=int32)),
 (1, array([0], dtype=int32)),
 (0, arr

In [ ]:
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(labels_test, labels_pred)

cm

array([[1511,   84],
       [ 239,  166]])